---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  labels:
    app: dummy-app
  namespace: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: srin64/dummy-app:latest
        ports:
        - containerPort: 5000
